package edu.cmu.tartan.socket;

public enum CommandResult {
	LOGIN_SUCCESS,
	LOGIN_FAIL,
	REGISTER_SUCCESS,
	REGISTER_FAIL,
	UPLOAD_SUCCESS,
	UPLOAD_FAIL,
	START_GAME_SUCCESS,
	START_GAME_FAIL,
	END_GAME_SUCCESS,
	END_GAME_FAIL,
	END_GAME_ALL_USER
	
}
